### DISCUSSION TITLE
新規注文登録時のPOSTリクエストについて（相談）

### DISCUSSION THREAD

**Discussion by tenk-9** [ARCircle/Kojirer#14] [General]
## 概要
新しい注文をDBに登録するAPIのリクエスト内容についてです．
受付係が端末で注文の詳細を入力し，DBに対して注文の内容をPOSTします．
1つの注文に対して複数の`丼インスタンス`が存在しうるため，POSTの内容をどのようにするか相談したいです（**相談**を参照）．
### リクエスト
二案の違いは，丼単位のPOSTにするか，注文体のPOSTにするかだけ．
#### 案1
- 注文された`丼`一つ一つに対して，POSTリクエストをする．
- どの`丼`が何番の注文か（`丼`がどの`call_num`を持つ`order`の子要素であるか）は`call_num`パラメータで表現する．

    ```yaml
    # postの内容はこんな感じ
    {
        "call_num": 1, 
        "size": 2, 
        "yasai": 2,
        "ninniku": 0,
        "karame": 4,
        "abura": 4,
        "toppings": {
            // 追加しなかったトッピングの情報はPOSTされない
            "mayo": 2,
            "onion": 1,
        },
    }
    ```
- 1つの注文に複数の`丼`が含まれる場合は，注文内の各`丼`についてPOSTリクエストをする．

#### 案2
- 1つの注文に対して，呼び出し番号（`call_num`）と，注文に含まれる丼の配列をPOSTする．
- どの`丼`が何番の注文か（`丼`がどの`call_num`を持つ`order`の子要素であるか）は内包関係で表現する．

    ```yaml
    # postの内容はこんな感じ
    {
        "call_num": 1, 
        "dons": [
            {
                "size": 2, 
                "yasai": 2,
                "ninniku": 0,
                "karame": 4,
                "abura": 4,
                "toppings": {
                    # 追加しなかったトッピングの情報はPOSTされない
                    "mayo": 2,
                    "onion": 1,
                },
                "sns_followed": true,
            },
            {
                "size": 1, 
                "yasai": 0,
                "ninniku": 3,
                "karame": 0,
                "abura": 4,
                "toppings": {
                    # 追加しなかったトッピングの情報はPOSTされない
                    "mayo": 8,
                    "curry": 1,
                    "lemon": 1,
                },
                "sns_followed": true,
            },
            # ...
        ]
    }
    ```
### レスポンス
最低限の要件は次の2点が返って来ることです．
- 成功時: SUCCESS (e.g. 201) コード
  - ボディは空でも良いです．
- 失敗時: 失敗コード
  - ボディ: 簡単に，どのようなエラーで落ちたのかを含むエラーメッセージ．

もし余裕があれば，次のようだと嬉しいです．
- 成功時: 追加した`丼`の詳細（POSTリクエストの内容と同じもの）が返って来る
- 失敗時: エラーメッセージ
### 相談
POSTの内容をどちらの案のようにしようか少し悩んでいます．**案1**では注文の区切りを明示せず，**案2**ではリクエスト単位で別の注文（注文の区切りが明示的）です．
どちらの案においても，リクエストに際するフロントエンド側の負荷はあまり変わりませんが，レスポンスに`POSTに成功したリクエストの内容`が含まれる場合，**案2**だと嬉しいです．
### 参考資料
- [用語定義](https://github.com/ARCircle/Kojirer/discussions/9#discussioncomment-8784803)
- [DBスキーマ](https://www.notion.so/DB-4d6845cc5574443d86a8c9442d2f655b?pvs=4#56e4975ccaeb42d4b248a780629508cd)（3/14参照）
- [草案（画像，①）](https://github.com/ARCircle/Kojirer/discussions/9#discussioncomment-8787404)
