### ISSUE TITLE
指定した調理状態の丼を取得するAPIの実装

### ISSUE THREAD

**Issue by tenk-9** [ARCircle/Kojirer#15]
- mod: 3/28 19:20, `調理ステータス`->`調理状態`

## 概要
`調理状態`と`件数`をパラメータとして，丼の情報を取得するAPIです．
`cook_status`, `amaount`をパラメータとして，`dons.status == cook_status`な丼について，
- その丼を含む注文の呼び出し番号
- その丼を含む注文の総丼数
- 丼のid
- 丼のサイズ
- ヤサイの量
- ニンニクの量
- カラメの量
- アブラの量
- トッピングの種類と量

を`amount`個返して欲しいです．
呼び出す端末と目的は次の2例を想定しています．
- 調理場の端末
  - 調理係が，どのような丼を作るべきか確かめるために参照します
  - 調理中（`1`）の丼を10件ほど取得したいです．
- 受け渡し口の端末
  - 受け渡し担当が，どの注文番号の客を呼び出すべきか知るために参照します
  - 呼び出し中（`2`）状態の丼を15件ほど取得したいです．
#### 調理状態について
`dons.status`の値です．ここでは，
`1`（調理中）->`2`（呼び出し中）->`3`（受け渡し済み）
の3段階と仮定します．
### リクエスト
- GET(status, amount)の形式です．
- パラメータは`status`と`amount`の二つです．
- エンドポイント名や実装（クエリパラメータ or パスパラメータ or else）はお任せします．
- 例えばエンドポイントは次のようなものが考えられます．
  - `koujirer/searchDish?status=1&amount=10`
  - `koujirer/dishes/cooking?amount=10`, `koujirer/dishes/calling?amount=5`
#### 成功時
- `status`条件に一致する`丼`の情報について，JSON形式で返して欲しいです．
- 例えば次のようです．
    ```yaml
    [
        {
            "order_call_id": 4,
            "order_dons_count": 2
            "size": 1,
            "yasai": 2,
            "ninniku": 0,
            "karame": 4,
            "abura": 4,
            "toppings": {
                # 追加しないトッピングはここに含まれない（可変長）
                "lemon": 5,
            },
        },
        {
            "order_call_id": 4,
            "order_dons_count": 2
            "size": 2,
            "yasai": 4,
            "ninniku": 4,
            "karame": 4,
            "abura": 4,
            "toppings": {
                "mayo": 10,
                "onion": 1,
            },
        },
        {
            "order_call_id": 5,
            "order_dons_count": 1
            "size": 1,
            "yasai": 0,
            "ninniku": 0,
            "karame": 0,
            "abura": 0,
            "toppings": {},
        },
        # ...
        # returnBody.length == parameter.amount
    ]
    ```
#### 失敗時
- 簡単な失敗理由を返して欲しいです．
### 参考資料
- [用語定義](https://github.com/ARCircle/Kojirer/discussions/9#discussioncomment-8784803)
- [DBスキーマ](https://www.notion.so/DB-4d6845cc5574443d86a8c9442d2f655b?pvs=4#56e4975ccaeb42d4b248a780629508cd)（3/14参照）
- [草案（画像，③）](https://github.com/ARCircle/Kojirer/discussions/9#discussioncomment-8787404)
