### ISSUE TITLE
新規注文を追加するAPIの実装

### ISSUE THREAD

**Issue by tenk-9** [ARCircle/Kojirer#18]
新しい注文をDBに登録するAPIの要件です．
- created: 3/15 16:35
- mod: 3/30 18:15, POSTリクエストの`toppings`項目の形式を変更

## 概要
受付係が端末で注文の詳細を入力し，DBに対して注文の内容をPOSTします．
送る内容は
- 注文の呼び出し番号
- 丼の情報（配列）
  - サイズ
  - 野菜の量
  - ニンニクの量
  - カラメの量
  - アブラの量
  - トッピングの種類と量（map）

です．

### リクエスト
- 1つの注文に対して，呼び出し番号（`call_num`）と，注文に含まれる丼の配列をPOSTする．
- どの`丼`が何番の注文か（`丼`がどの`call_num`を持つ`order`の子要素であるか）は内包関係で表現する．

    ```yaml
    # postの内容はこんな感じ
    {
        "call_num": 1, 
        "dons": [
            {
                "size": 2, 
                "yasai": 2,
                "ninniku": 0,
                "karame": 4,
                "abura": 4,
                "toppings": [
                    # 追加しなかったトッピングの情報はPOSTされない
                    {
                        "id": 1,
                        "label": "マヨ",
                        "amount": 1,
                    }
                ],
                "sns_followed": true,
            },
            {
                "size": 1, 
                "yasai": 0,
                "ninniku": 3,
                "karame": 0,
                "abura": 4,
                "toppings": [
                    # 追加しなかったトッピングの情報はPOSTされない
                    {
                        "id": 1,
                        "label": "マヨ",
                        "amount": 10,
                    },
                    {
                        "id": 2,
                        "label": "カレー粉",
                        "amount": 1,
                    },
                    {
                        "id": 5,
                        "label": "オニオン",
                        "amount": 3,
                    }
                ],
                "sns_followed": true,
            },
            # ...
        ]
    }
    ```
### レスポンス
最低限の要件は次の2点が返って来ることです．
- 成功時: SUCCESS (e.g. 201) コード
  - ボディは空でも良いです．
- 失敗時: 失敗コード
  - ボディ: 簡単に，どのようなエラーで落ちたのかを含むエラーメッセージ．

もし余裕があれば，次のようだと嬉しいです．
- 成功時: 追加した`丼`の詳細（POSTリクエストの内容と同じもの）が返って来る
- 失敗時: エラーメッセージ
### 参考資料
- [用語定義](https://github.com/ARCircle/Kojirer/discussions/9#discussioncomment-8784803)
- [DBスキーマ](https://www.notion.so/DB-4d6845cc5574443d86a8c9442d2f655b?pvs=4#56e4975ccaeb42d4b248a780629508cd)（3/14参照）
- [草案（画像，①）](https://github.com/ARCircle/Kojirer/discussions/9#discussioncomment-8787404)
